name: Deploy My Little React App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t henrychung/my-react-app -f Dockerfile.dev .
      - run: docker run -e CI=true henrychung/my-react-app npm test
